//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.10 at 05:51:51 PM EST 
//


package lk.express.metaxml.tbundle;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lk.express.metaxml.tbundle package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TaskBundle_QNAME = new QName("http://express.lk/2015/meta/taskBundle", "taskBundle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lk.express.metaxml.tbundle
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaskBundleType }
     * 
     */
    public TaskBundleType createTaskBundleType() {
        return new TaskBundleType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link OneTimeTaskType }
     * 
     */
    public OneTimeTaskType createOneTimeTaskType() {
        return new OneTimeTaskType();
    }

    /**
     * Create an instance of {@link RecurringTaskType }
     * 
     */
    public RecurringTaskType createRecurringTaskType() {
        return new RecurringTaskType();
    }

    /**
     * Create an instance of {@link TaskBundleType.Tasks }
     * 
     */
    public TaskBundleType.Tasks createTaskBundleTypeTasks() {
        return new TaskBundleType.Tasks();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskBundleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://express.lk/2015/meta/taskBundle", name = "taskBundle")
    public JAXBElement<TaskBundleType> createTaskBundle(TaskBundleType value) {
        return new JAXBElement<TaskBundleType>(_TaskBundle_QNAME, TaskBundleType.class, null, value);
    }

}
