<div class="modal-body">
    <div class="preloader-balls" ng-show="loading"></div>
    <div class="alert alert-danger" ng-show="errors && !loading">
        {{errors}}
    </div>
    <div class="well" ng-show="bookingData!==null && !loading">
        <div class="row">
            <div class="col-md-7 col-xs-12">
                <h3><?php echo $this->translate('Booking Details') ?> <small>{{bookingData.reference}}</small></h3>
                <table class="table">
                    <tr>
                        <th><?php echo $this->translate('Status') ?></th>
                        <th><?php echo $this->translate('Booking time') ?></th>
                        <th><?php echo $this->translate('Booking done by') ?></th>
                    </tr>
                    <tr>
                        <td>
                            <span class="label label-default"
                                  ng-class="{'label-success': (bookingData.status.code=='CONF'), 'label-danger': (bookingData.status.code=='CANC')}">
                                {{bookingData.status.name}}
                            </span>
                        </td>
                        <td>{{bookingData.bookingTime | date:'yyyy-MM-dd @ h:mma'}}</td>
                        <td>{{bookingData.user.firstName}} {{bookingData.user.lastName}}</td>
                    </tr>
                </table>
                <h3><?php echo $this->translate('Client') ?></h3>
                <table class="table">
                    <tr>
                        <th><?php echo $this->translate('Name') ?></th>
                        <th><?php echo $this->translate('NIC') ?></th>
                        <th><?php echo $this->translate('Phone') ?></th>
                        <th><?php echo $this->translate('Seats') ?></th>
                    </tr>
                    <tr>
                        <td>{{bookingData.client.name}}</td>
                        <td>{{bookingData.client.nic}}</td>
                        <td>{{bookingData.client.mobileTelephone}}</td>
                        <td>
                            <ul ng-repeat="item in bookingData.bookingItems">
                                <li ng-repeat="seat in item.passengers">{{seat.seatNumber}}</li>
                            </ul>
                        </td>
                    </tr>
                </table>
                <h3 ng-show="bookingData.agent">Agent</h3>
                <p ng-show="bookingData.agent">{{bookingData.agent.name}}</p>
                <h3><?php echo $this->translate('Remarks') ?></h3>
                <p>{{bookingData.remarks}}</p>
            </div>
            <div class="col-md-5 col-xs-12">
                <h3><?php echo $this->translate('Cancel booking') ?></h3>

                <form class="" name="cancelform" ng-submit="cancelform.$valid && cancelBooking()" novalidate>
                    <div class="form-group">
                        <label><?php echo $this->translate('Cancellation cause') ?></label>
                        <select ng-model="cancel.cause" name="cause" class="form-control" ng-required="true">
                            <option value="ClientRequested"><?php echo $this->translate('Cancel : Requested by client') ?></option>
                            <option value="DataEntryError"><?php echo $this->translate('Cancel : Data entry error') ?></option>
                            <option value="Other"><?php echo $this->translate('Cancel : Other (Please specify)') ?></option>
                        </select>
                        <div ng-show="cancelform.$submitted || cancelform.cause.$touched">
                            <p class="bg-danger text-danger error" ng-show="cancelform.cause.$error.required">
                                * <?php echo $this->translate('Please select a cancellation cause') ?></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label><?php echo $this->translate('Cancellation remarks') ?></label>
                        <textarea ng-model="cancel.remark" name="remark" class="form-control" ng-required="false"></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Cancel booking') ?></button>
                </form>
            </div>
        </div>
    </div>
</div>