<h1><?php echo $this->translate('Terms & Conditions') ?></h1>
<div class="container">
   <p dir="ltr" class="text-static">
	SLTB EXPRESS Services are regulated under terms and conditions set forth herein to provide a better passenger experience and to develop a well regulated and disciplined service with passenger transport Operator and transport Operator’s  staff. SLTB EXPRESS is an online value added services provider. It does NOT operate bus services of its own and have tied up with Sri Lanka Transport Board hereinafter referred to as the “Operator”for offering services on bus  ticket reservations. User of SLTB EXPRESS; when obtaining services from the Operator, 
	constitutes a separate agreement outside of SLTB EXPRESS in relation to operational affairs specified but not limiting to :
   </p>
   
   <ol type="a">
	<li><p dir="ltr" class="text-static">  Bus Schedule cancellations</p> </li>
	<li><p dir="ltr" class="text-static">  Bus breakdowns and alternative arrangements</p> </li>
	<li><p dir="ltr" class="text-static">  Refunds in the event of cancellations by the Operator</p></li>
   </ol>
   <p dir="ltr"  class="text-static">Such activities relating to operational affairs are governed by general terms and conditions set by Sri Lanka Transport Board and SLTB EXPRESS holds no responsibility whatsoever.</p>
   <p class="red-text" dir="ltr"> Binding Contract</p>
   <p dir="ltr" class="text-static"> 
	The Use Terms & Conditions formulate a binding contract between the User and SLTB EXPRESS. By using SLTB EXPRESS services, you agree to be bound by the terms and conditions shown below. If you do not agree our terms and conditions we are not in a position to provide you our services and we do apologize for that. Our Terms and Conditions are subject to change at any time without a prior notice. To make sure you are aware of any changes, please review this section periodically.
   </p>
   <br>
   <ol >
      <li dir="ltr">
         <p dir="ltr" class="text-static"> The Passenger should be present at the correct bus terminal which the bus is scheduled to departure, 15 minutes before the Estimated Time of Departure (ETD) of the reserved bus service.</p>
      </li>
      <li dir="ltr">
         <p dir="ltr" class="text-static"> SLTB EXPRESS is not liable for any damage or inconvenience arising out of any miscommunication, delays of the passenger or any misleading and or false  information provided by the Passenger. </p>
      </li>
      <li dir="ltr">
         <p dir="ltr" class="text-static"> SLTB EXPRESS and/or Sri Lanka Transport Board (the partnered transit Operator) reserve rights to change the schedule and/or cancel, terminate, postpone, divert, reschedule, delay any bus/coach or detour, anytime after your reservation without a prior notice. This may be due to safety or reasonably considered and justified circumstances beyond our control. Notwithstanding the circumstances SLTB EXPRESS shall not be liable for any damages or inconvenience caused to the Passenger. </p>
      </li>
      <li dir="ltr">
         <p dir="ltr" class="text-static"> SLTB EXPRESS pursuing Operator’s policy shall not allow reservation cancellations and shall not process requests to refund pertaining to confirmed reservations. Nonetheless the cancellations by the Operator are dealt entirely by relevant bus Depot of the Operator and the User/Passenger may directly contact the Depot of the Operator with regard to such cancellations made by the Operator. </p>
      </li>
      <li dir="ltr">
         <p dir="ltr" class="text-static"> The Passenger is required to furnish the Ticket (eTicket/mTicket)  or the booking confirmation SMS to the Bus Conductor along with the National Identity Card/Driver's License/Passport to verify the identity of the prepaid Passenger. Additionally, the Passengers should agree to submit one of the aforesaid personal identification documents for inspection by Bus Operator's designated staff or relevant authorities to verify the identity in the event of a security concern at any given time throughout the Passenger's engagement with the Services offered by the SLTB EXPRESS and bus Operator.  </p>
      </li>
      <li dir="ltr">
         <p dir="ltr" class="text-static"> SLTB EXPRESS is not liable for any delays before and/or during the journey and for the road accidents at any point in time during the  Passenger's engagement with the Services offered by both SLTB EXPRESS and Bus Operator </p>
      </li>
	  <li dir="ltr">
         <p dir="ltr" class="text-static"> eTickets reserved via SLTB EXPRESS are not transferable whatsoever. It is User's sole responsibility to provide accurate contact information of all intended Passengers per seat reserved. Users/Passengers agree that inaccurate Passenger details may lead in prohibiting the embarkation. </p>
		 <p dir="ltr" class="text-static"> Our responsibilities include:</p>
		 <ol>
			<li dir="ltr"><p dir="ltr" class="text-static">Issuing a valid ticket (a ticket that will be accepted by the bus Operator) on behalf of the Operator.</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">Providing customer support and information in case of any delays/inconvenience</p></li>			
		 </ol>
		 
		 <p dir="ltr class="text-static"> Our responsibilities do NOT include:</p>
		 <ol>
			<li dir="ltr"><p dir="ltr" class="text-static">The bus operator’s bus not departing/reaching on time</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">The bus operator’s staff being rude and/or their discipline or their conduct whatsoever</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">The bus operator’s bus seats, condition inside the bus etc. not being up to the User/Passenger’s expectation</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">The bus operator canceling the trip due to unavoidable reasons</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">The baggage of the User/Passenger getting lost/stolen/damaged or not being able to load to the bus or being charged separately</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">The bus operator changing a User/Passenger’s seat at the last minute to accommodate a separate passenger</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">The User/Passenger waiting at the wrong boarding point. User/Passenger agree to contact the bus operator to find out the exact boarding point in the event that the User/Passenger is not aware of the exact boarding point</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">The bus operator changing the boarding point and/or using a pick-up vehicle at the boarding point to take User/Passenger to the bus departure point</p></li>
			<li dir="ltr"><p dir="ltr" class="text-static">Any inconvenience caused by the act of other passengers regardless their source of ticket reservation</p></li>
		</ol>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static"> The arrival and departure times mentioned on the ticket are only tentative time schedules</p>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static"> 
		In case a booking confirmation e-mail and SMS gets delayed or fails because of technical reasons or as a result of incorrect e-mail ID/phone number provided by the user etc, a ticket will be considered 'booked' as long as the ticket shows up on the confirmation page of SLTB EXPRESS platform</p>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static"> 
			SLTB EXPRESS will not be liable to you or to any other person for any direct, indirect, incidental, punitive or consequential loss, damage, cost or expense of any kind whatsoever and howsoever caused out of the information derived from you through your usage of this Site. In no event shall SLTB EXPRESS be liable for any direct, indirect, punitive, incidental, special, or consequential damages arising out of information provided on the website in so far as such information is derived from other service providers
		</p>
	  </li>
   </ol>
   
	<p class="red-text" dir="ltr"> Communication Policy</p>
	<ol>
	 <li dir="ltr">
		<p dir="ltr" class="text-static"> By accepting the terms and conditions the User/Passenger accepts that SLTB EXPRESS may send the alerts to the mobile phone number provided by the User while registering for the service or to any such number replaced and informed by the User. The User/Passenger acknowledges that the alerts will be received only if the mobile phone is on active mode and technically acceptable condition to receive the SMS timely manner.</p>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static"> SLTB EXPRESS shall make best efforts to provide the service and it shall be deemed that the customer shall have received the information sent from SLTB EXPRESS as an alert on the mobile phone number provided during the course of ticket booking and SLTB EXPRESS shall not be under any obligation to confirm the authenticity of the person(s) receiving the alert. The User/Passenger shall not have the right to hold SLTB EXPRESS liable for non-availability of the service in any manner whatsoever.</p>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static"> The User/Passenger acknowledges that the SMS service provided by SLTB EXPRESS is an additional facility provided for the User/Passenger’s convenience and that it may be susceptible to error, omission and/ or inaccuracy. In the event the User/Passenger observes any error in the information provided in the alert, SLTB EXPRESS shall be immediately informed about the same by the User/Passenger and SLTB EXPRESS will make best possible efforts to rectify the error as early as possible. The User/Passenger  shall not hold SLTB EXPRESS liable for any loss, damages, claim, expense including legal cost that may be incurred/ suffered by the User/Passenger on account of the SMS facility.</p>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static">The User/Passenger acknowledges that the clarity, readability, accuracy, and promptness of providing the service depend on many factors including the infrastructure, connectivity of the Mobile Telecommunication Service Provider. SLTB EXPRESS shall not be responsible for any non-delivery, delayed delivery or distortion of the alert in any way whatsoever. </p>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static">The User/Passenger agrees to indemnify and hold SLTB EXPRESS harmless from any damages, claims, demands, proceedings, loss, cost, charges and expenses whatsoever including legal charges and attorney fees which SLTB EXPRESS may at any time incur, sustain, suffer or be put to as a consequence of or arising out of: </p>
		<ol>
			<li dir="ltr">
				<p dir="ltr" class="text-static">misuse, improper or fraudulent information provided by the customer</p>
			</li>
			<li dir="ltr">
				<p dir="ltr" class="text-static">the User  providing incorrect number or providing a number that belongs to that of an unrelated third party, and/or</p>
			</li>
			<li dir="ltr">
				<p dir="ltr" class="text-static">the User/Passenger receiving any message relating to the reservation number, travel itinerary information, booking confirmation, modification to a ticket, cancellation of ticket, change in bus schedule, delay, and/or rescheduling from SLTB EXPRESS and/or any third party</p>
			</li>
		</ol>
	  </li>
	  <li dir="ltr">
		<p dir="ltr" class="text-static">By accepting the terms and conditions the User/Passenger acknowledges and agrees that SLTB EXPRESS or transit service operator’s staff, may call the mobile phone number provided by the User while registering for the service or to any such number replaced and informed by the User/Passenger, for the purpose of collecting feedback from the User/Passenger regarding their travel, the bus facilities and/or services of the bus operator.</p>
	  </li>
	  	  <li dir="ltr">
		<p dir="ltr" class="text-static">Grievances and claims related to the bus journey should be reported to SLTB EXPRESS support team within 24 hours of your journey start time.</p>
	  </li>
    </ol>
	<br/>
</div>