
<h5 class="header-text bold-text">Bus Schedule</h5>

<div loading-container="tableParams.settings().$loading">
    <table ng-table="tableParams" class="table resulttable" show-filter="true" template-pagination="searchTablePager">
        <tbody>
        <tr ng-repeat="schedule in $data" show-seats ng-class="getTrClass(schedule)">
            <!-- main row -->
            <td data-title="'Departure Time'"sortable="'departureTime'" filter="{ 'departureTime': 'text' }">
                <b>{{schedule.departureTime | date:'yyyy-MM-dd @ h:mma'}}</b>
            </td>
            <td data-title="'Arrival Time'"sortable="'arrivalTime'" filter="{ 'arrivalTime': 'text' }">
                <b>{{schedule.arrivalTime | date:'yyyy-MM-dd @ h:mma'}}</b>
            </td>
            <td data-title="'Bus Name'" filter="{ 'bus.plateNumber': 'text' }">
                {{schedule.bus.plateNumber}} {{schedule.bus.name}}
            </td>
            <td data-title="'Route'">
                <ul>
                    <li ng-repeat="route in schedule.bus.busRoutes">
                        {{route.routeNumber}} : {{route.name}}
                    </li>
                </ul>
            </td>
        </tr>
        <tr ng-show="!$data.length">
            <td colspan="10"><b class="">No Results!</b> <span class="text-muted"> - Can't find a schedule. Try again.</span></td>
        </tr>
        </tbody>
    </table>
</div>

<script type="text/ng-template" id="searchTablePager">
    <ul class="pagination ng-table-pagination">
        <li ng-class="{'disabled': !page.active}" ng-repeat="page in pages" ng-switch="page.type">
            <a ng-switch-when="prev" ng-click="params.page(page.number)" href="">&laquo;</a>
            <a ng-switch-when="first" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a>
            <a ng-switch-when="page" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a>
            <a ng-switch-when="more" ng-click="params.page(page.number)" href="">&#8230;</a>
            <a ng-switch-when="last" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a>
            <a ng-switch-when="next" ng-click="params.page(page.number)" href="">&raquo;</a>
        </li>
    </ul>
</script>