
<div class="container">
    <div class="gap"></div>
    <div class="row">
        <div class="col-md-12 text-center">
            <h2><?php echo $this->translate('Welcome to SLTB EXPRESS online services!') ?></h2>
            <h4><?php echo $this->translate('Your online portal to reserve Sri Lanka Transport Board passenger transit services, across Sri Lanka.') ?></h4>
            <p><?php echo $this->translate('Want your public transportation and online bus ticket booking issues sorted? We at SLTB EXPRESS  will attend to all your online bus seat reservations, booking requirements and make sure that you have a safe and a comfortable journey. A unique platform of online bus booking Sri Lanka has to offer, we have made it easy for you to reserve your seats to avoid hassle and inconveniences, reach your destination with the comfort that you deserve. Happy Journeys!') ?></p>
        </div>
    </div>
    <div class="gap hidden-xs"></div>
</div>
<div class="container hidden-xs">
    <h2 class="text-center"><?php echo $this->translate('Popular SLTB EXPRESS Bus Routes'); ?></h2>
    <p class="text-center"><?php echo $this->translate('All passenger transit services across Sri Lanka'); ?> </p>
    <div class="gap gap-small"></div>
    <div class="row row-wrap">
        <div class="col-1in5">
            <div class="route-box blue0">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Ampara/12/287/" >
                    	<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Ampara') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box blue1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Anuradhapura/12/308/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Anuradhapura ') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box blue2">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Badulla/12/122/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Badulla') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box green1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Trincomalee/12/126/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Trincomalee') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box yellow1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Jaffna/12/120/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Jaffna') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row row-wrap">
        <div class="col-1in5">
            <div class="route-box orange1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Kalmunai/12/124/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Kalmunai') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box orange2">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Akkaraipattu/12/125/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Akkaraipattu') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box brown1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Kataragama/12/14/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Kataragama') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box red1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Hatton/12/366/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Hatton') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box purple1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
					<a class="hover-img curved" target="_self" href="/bus/search/Colombo/Mannar/12/189/" >
						<div class="route-box-circle"><i class="fa fa-bus"></i></div>
						<h3><?php echo $this->translate('Colombo') ?> - <?php echo $this->translate('Mannar') ?></h3>
						<div class="route-cont-separator"></div>
					</a>
                </div>
            </div>
        </div>
    </div>

</div>
