<?php
//change layout
$this->layout('layout/layout_basic');
?>

<div class="full-page">
    <div class="bg-holder full">
        <div class="bg-mask"></div>
        <div class="bg-blur" style="background-image:url(/img/404.jpg);"></div>
        <div class="bg-holder-content full text-white">
            <a class="logo-holder" href="/">
                <img src="/img/BusBooking-logo-40x40.png" alt="BusBooking Logo" title="BusBooking Logo" />
            </a>
            <div class="full-center">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <p class="text-hero">404</p>
                            <h1><?php echo $this->translate('Page is not found') ?></h1>
                            <p><?php echo $this->translate('Did you spell the URL correctly? We don\'t have a page for that URL.') ?> <?php echo $this->message ?></p>
                            <a class="btn btn-white btn-ghost btn-lg mt5" href="<?php echo (isset($_SERVER['HTTP_REFERER']) && !empty($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '/') ?>">
                                <i class="fa fa-long-arrow-left"></i> <?php echo $this->translate('go Back') ?>
                            </a>

                            <?php if (isset($this->layout()->display_exceptions) && $this->layout()->display_exceptions): ?>

                                <?php if (isset($this->reason) && $this->reason): ?>

                                    <?php
                                    $reasonMessage= '';
                                    switch ($this->reason) {
                                        case 'error-controller-cannot-dispatch':
                                            $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
                                            break;
                                        case 'error-controller-not-found':
                                            $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
                                            break;
                                        case 'error-controller-invalid':
                                            $reasonMessage = $this->translate('The requested controller was not dispatchable.');
                                            break;
                                        case 'error-router-no-match':
                                            $reasonMessage = $this->translate('The requested URL could not be matched by routing.');
                                            break;
                                        default:
                                            $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
                                            break;
                                    }
                                    ?>

                                    <p><?php echo $reasonMessage ?></p>

                                <?php endif ?>

                                <?php if (isset($this->controller) && $this->controller): ?>

                                    <dl>
                                        <dt><?php echo $this->translate('Controller') ?>:</dt>
                                        <dd><?php echo $this->escapeHtml($this->controller) ?>
                                            <?php
                                            if (isset($this->controller_class)
                                                && $this->controller_class
                                                && $this->controller_class != $this->controller
                                            ) {
                                                echo '(' . sprintf($this->translate('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
                                            }
                                            ?>
                                        </dd>
                                    </dl>

                                <?php endif ?>


                                <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
                                    <hr/>
                                    <h2><?php echo $this->translate('Additional information') ?>:</h2>
                                    <h3><?php echo get_class($this->exception); ?></h3>
                                    <dl>
                                        <dt><?php echo $this->translate('File') ?>:</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
                                        </dd>
                                        <dt><?php echo $this->translate('Message') ?>:</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
                                        </dd>
                                        <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                                        <dd>
                                            <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
                                        </dd>
                                    </dl>
                                    <?php
                                    $e = $this->exception->getPrevious();
                                    if ($e) :
                                        ?>
                                        <hr/>
                                        <h2><?php echo $this->translate('Previous exceptions') ?>:</h2>
                                        <ul class="unstyled">
                                            <?php while($e) : ?>
                                                <li>
                                                    <h3><?php echo get_class($e); ?></h3>
                                                    <dl>
                                                        <dt><?php echo $this->translate('File') ?>:</dt>
                                                        <dd>
                                                            <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                                                        </dd>
                                                        <dt><?php echo $this->translate('Message') ?>:</dt>
                                                        <dd>
                                                            <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                                                        </dd>
                                                        <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                                                        <dd>
                                                            <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                                                        </dd>
                                                    </dl>
                                                </li>
                                                <?php
                                                $e = $e->getPrevious();
                                            endwhile;
                                            ?>
                                        </ul>
                                    <?php endif; ?>

                                <?php else: ?>

                                    <h3><?php echo $this->translate('No Exceptions available') ?></h3>

                                <?php endif ?>

                            <?php endif ?>

                        </div>
                    </div>
                </div>
            </div>
            <?php
            echo $this->navigation('Navigation')
                ->menu()
                ->setUlClass('footer-links');
            ?>
        </div>
    </div>
</div>

