
<div class="container hidden-xs">
    <div class="gap gap-small hidden-xs hidden-sm"></div>
    <div class="row">
        <div class="col-md-12 text-center">
            <h2><?php echo $this->translate('#1 Website to Reserve Your Bus Seat! 24x7') ?></h2>
            <h4><?php echo $this->translate('Fully Fledged Booking & Reservation Services for Public Transport Services') ?></h4>
            <p><?php echo $this->translate('Homepage: #1 Website text') ?></p>
        </div>
    </div>
    <div class="gap hidden-xs"></div>
    <div class="row hidden-xs">
        <div class="col-md-12">
            <div class="row row-wrap text-center">
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="thumb">
                        <header class="thumb-header">
                            <i class="fa fa-tablet box-icon-black round box-icon-big box-icon-inline animate-icon-top-to-bottom"></i>
                        </header>
                        <div class="thumb-caption">
                            
                            <h5 class="thumb-title"><a class="text-darken" href="#"><?php echo $this->translate('From Anywhere'); ?></a></h5>
                            <p class="thumb-desc"><?php echo $this->translate('From Anywhere text') ?></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="thumb">
                        <header class="thumb-header">
                            <i class="fa fa-thumbs-o-up box-icon-black round box-icon-big box-icon-inline animate-icon-top-to-bottom"></i>
                        </header>
                        <div class="thumb-caption">
                            
                            <h5 class="thumb-title"><a class="text-darken" href="#"><?php echo $this->translate('Reserve & Save') ?></a></h5>
                            <p class="thumb-desc"><?php echo $this->translate('Reserve & Save text') ?></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="thumb">
                        <header class="thumb-header">
                            <i class="fa fa-life-ring box-icon-black round box-icon-big box-icon-inline animate-icon-top-to-bottom"></i>
                        </header>
                        <div class="thumb-caption">
                            
                            <h5 class="thumb-title"><a class="text-darken" href="#"><?php echo $this->translate('Passenger Support') ?></a></h5>
                            <p class="thumb-desc"><?php echo $this->translate('Passenger Support text') ?></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3 col-xs-6">
                    <div class="thumb">
                        <header class="thumb-header">
                            <i class="fa fa-lock box-icon-black round box-icon-big box-icon-inline animate-icon-top-to-bottom"></i>
                        </header>
                        <div class="thumb-caption">
                            
                            <h5 class="thumb-title"><a class="text-darken" href="#"><?php echo $this->translate('100% Secure') ?></a></h5>
                            <p class="thumb-desc"><?php echo $this->translate('100% Secure text') ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="gap hidden-xs"></div>
</div>
<div class="bg-holder hidden-xs">
    <div class="bg-content">
        <uib-carousel class="normal-slider" interval="3000" ng-init="slides=[
                        {l: 'BusBooking.lk_CBL_Advertisement.png', alt: 'Bus Seat booking'},
                        {l: 'BusBooking.lk_Conductor_on_internet.png', alt: 'Condictor in Internet'}
                        ]">
            <uib-slide ng-repeat="slide in slides" active="slide.active">
                <img ng-src="/img/carousel/{{slide.l}}" alt="{{slide.alt}}" style="margin:auto; height: 100%;">
            </uib-slide>
        </uib-carousel>
    </div>
</div>
<div class="container hidden-xs">
    <div class="gap"></div>
    <h2 class="text-center"><?php echo $this->translate('Top Bus Routes & Bus Schedules'); ?></h2>
    <div class="row row-wrap">
        <div class="col-md-3 col-sm-6">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Kataragama/12/14/">
                        <img src="/img/top-destinations/kataragama.jpg" alt="Bus seat booking - Colombo - Kataragama" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Kataragama/12/14/"><?php echo $this->translate('Colombo - Kataragama'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('From CMB: 06.00 AM (Super Luxury)'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('From KTG: 02.30 AM (Super Luxury)'); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Badulla/12/122/">
                        <img src="/img/top-destinations/Badulla.jpg" alt="Bus seat booking - Colombo - Badulla" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Badulla/12/122/"><?php echo $this->translate('Colombo - Badulla'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Badulla onward'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Badulla return'); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Tangalle/12/11/">
                        <img src="/img/top-destinations/Galle1.jpg" alt="Bus seat booking - Colombo - Tangalle" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Tangalle/12/11/"><?php echo $this->translate('Colombo - Tangalle'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('From CMB: 06.30 AM (Super Luxury)'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('From TGL: 05.00 AM (Super Luxury)'); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Jaffna/12/120/">
                        <img src="/img/top-destinations/Jaffna2.jpg" alt="Bus seat booking - Colombo - Jaffna" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Jaffna/12/120/"><?php echo $this->translate('Colombo - Jaffna'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Jaffna onward'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Jaffna return'); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row row-wrap hidden-sm hidden-xs">
        <div class="col-md-3">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Batticaloa/12/187/">
                        <img src="/img/top-destinations/batticaloa.jpg" alt="Bus seat booking - Colombo - Batticaloa" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Batticaloa/12/187/"><?php echo $this->translate('Colombo - Batticaloa'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Batticaloa onward'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Batticaloa return'); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Matara/12/15/">
                        <img src="/img/top-destinations/Matara1.jpg" alt="Bus seat booking - Colombo - Matara" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Matara/12/15/"><?php echo $this->translate('Colombo - Matara'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Matara onward'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Matara return'); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Trincomalee/12/126/">
                        <img src="/img/top-destinations/Trinco1.jpg" alt="Bus seat booking - Colombo - Trinco" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Trincomalee/12/126/"><?php echo $this->translate('Colombo - Trinco'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('From CMB: 11.00 PM (Super Luxury)'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('From TCM: 11.00 PM (Super Luxury)'); ?></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="thumb">
                <header class="thumb-header">
                    <a class="hover-img curved" target="_self" href="/bus/search/Colombo/Nuwaraeliya/12/116/">
                        <img src="/img/top-destinations/NuwaraEliya.jpg" alt="Bus seat booking - Colombo - Nuwaraeliya" title="" />
                    </a>
                </header>
                <div class="thumb-caption">
                    <h4 class="thumb-title"><a class="text-darken" target="_self" href="/bus/search/Colombo/Nuwaraeliya/12/116/"><?php echo $this->translate('Colombo - Nuwaraeliya'); ?></a></h4>
                    <div class="thumb-caption">
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Nuwaraeliya onward'); ?></p>
                        <p class="thumb-desc"><?php echo $this->translate('Colombo - Nuwaraeliya return'); ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
