<?php 
$startTime = date("Y-m-d H:i:s");
$convertedTime = date('Y-m-d h:i:s A P',strtotime('+10 minutes',strtotime($startTime)));
?>

<div ng-controller="placeBookingRoute" style="text-align:center" >
	<i class=" fa fa-warning" style="font-size:35px; color:red;">
		Complete the payment  before : <?php echo $convertedTime.' UTC'; ?> 
	</i>
</div>
<div class="gap gap-small"></div>

<div class="payfram-container" payment-iframe="">
    <div class="payfram-preload">
        <h3 class="text">
            Connecting to <b class="green-text">secure</b> payment gateway...
        </h3>
        <div class="preloader-balls"></div>
    </div>
    <iframe id="paymentiframe" ng-src="{{iframeUrl}}" class="pay-iframe"></iframe>
</div>