
<div class="container">
    <div class="gap"></div>
    <div class="row">
        <div class="col-md-12 text-center">
            <h2><?php echo $this->translate('Welcome to Superline online services!') ?></h2>
            <h4><?php echo $this->translate('Your online portal to reserve super luxury passenger transport services, across Sri Lanka.') ?></h4>
            <p><?php echo $this->translate('Homepage: #1 Website text') ?></p>
        </div>
    </div>
    <div class="gap hidden-xs"></div>
</div>
<div class="container hidden-xs">
    <h2 class="text-center"><?php echo $this->translate('Available Bus Routes'); ?></h2>
    <p class="text-center">Super luxury bus service across Sri Lanka</p>
    <div class="gap gap-small"></div>
    <div class="row row-wrap">
        <div class="col-1in5">
            <div class="route-box blue0">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Colombo - Badulla</h3>
                    <div class="route-cont-separator"></div>
                    <p>Terminal In : 22.00<br/>
                        From Colombo : 23.00</p>
                    <i class="">Duration: 6 hours</i>
                    <p class="price">LKR 860.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box blue1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Colombo - Passara</h3>
                    <div class="route-cont-separator"></div>
                    <p>Terminal In : 21.00<br/>
                        From Colombo : 22.00</p>
                    <i class="">Duration: 6 1/2 hours</i>
                    <p class="price">LKR 860.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box blue2">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Wellawatta - Trincomalee</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Wellawatta : 22.00<br/>
                        From Colombo : 23.00
                    </p>
                    <i class="">Duration: 6 hours</i>
                    <p class="price">LKR 865.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box green1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Colombo - Kalmunei</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Wellawatta : 20.00<br/>
                        From Colombo : 21.00
                    </p>
                    <i class="">Duration: 9 hours</i>
                    <p class="price">LKR 1100.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box yellow1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Wellawatta - Akkareipattu</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Wellawatta : 20.00<br/>
                        From Colombo : 21.00
                    </p>
                    <i class="">Duration: 9 1/2 hours</i>
                    <p class="price">LKR 1100.00</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row row-wrap">
        <div class="col-1in5">
            <div class="route-box orange1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Badulla - Colombo</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Badulla : 23.00<br/>
                        From Bandarawela : 23.50
                    </p>
                    <i class="">Duration: 6 hours</i>
                    <p class="price">LKR 860.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box orange2">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Passara - Colombo</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Passara : 22.00<br/>
                        From Badulla : 23.00
                    </p>
                    <i class="">Duration: 6 1/2 hours</i>
                    <p class="price">LKR 860.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box brown1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Trincomalee - Wellawatta</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Trincomalee : 23.00<br/>
                    </p>
                    <i class="">Duration: 6 hours</i>
                    <p class="price">LKR 865.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box red1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Kalmunei - Wellawatta</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Kalmunei : 23.00<br/>
                    </p>
                    <i class="">Duration: 9 hours</i>
                    <p class="price">LKR 1100.00</p>
                </div>
            </div>
        </div>
        <div class="col-1in5">
            <div class="route-box purple1">
                <div class="route-box-bg"></div>
                <div class="route-box-content">
                    <div class="route-box-circle"><i class="fa fa-bus"></i></div>
                    <h3>Akkareipattu - Wellawatta</h3>
                    <div class="route-cont-separator"></div>
                    <p>
                        From Akkareipattu : 21.00<br/>
                    </p>
                    <i class="">Duration: 9 1/2 hours</i>
                    <p class="price">LKR 1100.00</p>
                </div>
            </div>
        </div>
    </div>

</div>
