<div class="row">
    <div class="col-md-12">
        <ul class="nav nav-tabs" id="myTab">
            <li><a href="#/">Home</a></li>
            <li class="dropdown" dropdown>
                <a class="dropdown-toggle" uib-dropdown-toggle>Buses
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#/search_bus">Buses</a></li>
                    <li><a href="#/add_bus">Add Buses</a></li>
                </ul>
            </li>
            <li class="dropdown" dropdown>
                <a class="dropdown-toggle" uib-dropdown-toggle>Schedules
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#view_schedule">View Schedules</a></li>
                    <li><a href="#add_schedule">Add Schedule</a></li>
                </ul>
            </li>
            <li class="dropdown" dropdown>
                <a class="dropdown-toggle" uib-dropdown-toggle>Users
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#view_users">View Users</a></li>
                    <li><a href="#add_user">Add User</a></li>
                </ul>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active">
                <div ng-view></div>
            </div>
        </div>
    </div>
</div>

<script type="text/ng-template" id="home">
    <h1>Configurations</h1>
    <p>Main system configurations and actions</p>
</script>