//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.10 at 05:51:51 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://express.lk/2015/meta", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lk.express.metaxml.meta;
