<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Express.lk ')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/min/core.min.css', 'all');
    ?>

    <!-- Scripts -->
    <?php
//    echo $this->headScript()
//        ->prependFile($this->basePath() . '/min/front.min.js')
//        ->prependFile($this->basePath() . '/min/core.min.js')
//        ->prependFile($this->basePath() . '/min/ltie9.min.js', 'text/javascript', array('conditional' => 'lt IE 9',));
    ?>

</head>
<body>
<div class="container">

    <?php echo $this->content; ?>

</div>

</body>
</html>