<?php echo $this->doctype(); ?>
<html lang="en" ng-app="expressFront">

<?php echo $this->partial('partial/head-common') ?>

<body>

<base href="/">

<div class="global-wrap">

    <?php
    echo $this->content;
    ?>

</div>

<div ng-cloak class="alert alert-success common-success ng-hide ng-cloak" ng-show="Global.success.isSuccess">
    <span class="common-success-text">
        <i class="fa fa-thumbs-up"></i>&nbsp;&nbsp;{{Global.success.message}}
    </span>
</div>

<div ng-cloak class="alert alert-danger common-error ng-hide ng-cloak" ng-show="Global.error.hasError">
    <span class="common-error-text">
        <i class="fa fa-warning"></i>&nbsp;&nbsp;{{Global.error.message}}
    </span>
</div>

<div ng-cloak class="main-preloader ng-hide ng-cloak" ng-show="_showPreLoader">
    <div class="preload-image"></div>
</div>

<?php echo $this->inlineScript() ?>

</body>
</html>