<?php echo $this->doctype(); ?>
<html lang="en" ng-app="expressFront" class="full js no-touch backgroundsize csstransforms3d csstransitions">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('BusBooking.lk')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/min/core.min.css?'. filemtime('public/min/core.min.css'))
        ->prependStylesheet($this->basePath() . '/min/libs.min.css?'. filemtime('public/min/libs.min.css'));
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/min/front.min.js?'. filemtime('public/min/front.min.js'))
        ->prependFile($this->basePath() . '/min/core.min.js?'. filemtime('public/min/core.min.js'))
        ->prependFile($this->basePath() . '/min/libs.min.js?'. filemtime('public/min/libs.min.js'))
        ->prependFile($this->basePath() . '/min/ltie9.min.js?'. filemtime('public/min/ltie9.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
    ?>
	<style>
		ol {
		  counter-reset: section;
		  list-style-type: none;
		}

		li:before {
		  counter-increment: section;
		  content: counters(section, ".") "." counters(section, ".") " ";
		}
</style>
	
<script>
(function(h,o,t,j,a,r){
h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
h._hjSettings={hjid:985327,hjsv:6};
a=o.getElementsByTagName('head')[0];
r=o.createElement('script');r.async=1;
r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
a.appendChild(r);
})(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-58142174-2', 'auto');
        ga('send', 'pageview');

    </script>

</head>
<body class="full" ng-controller="searchCommon">

    <!-- end nav -->
    <base href="/">
    <div class="global-wrap">
        <?php echo $this->content; ?>
    </div>

<!-- /container -->
    <div ng-cloak class="alert alert-success common-success ng-hide ng-cloak" ng-show="Global.success.isSuccess">
        <span class="common-success-text">{{Global.success.message}}</span>
    </div>

    <div ng-cloak class="alert alert-danger common-error ng-hide ng-cloak" ng-show="Global.error.hasError">
        <span class="common-error-text">{{Global.error.message}}</span>
    </div>

    <div ng-cloak class="main-preloader ng-hide ng-cloak" ng-show="_showPreLoader">
        <div class="preload-image"></div>
    </div>

<?php echo $this->inlineScript() ?>
</body>
</html>