<div ng-controller="reportController">
    <div class="row list-header">
        <div class="col-lg-12">
            <div class="page-header">
                <h1><span>Depot Operated Bus Fare </span></h1>
            </div>
        </div>
    </div>
    <div class="row">
        <form class="form-horizontal" ng-submit="loadDepotBusFareReport();" ng-init="currentRpt='depotBusFareReport'" >
            <div class="filter input-string">
                <div class="col-sm-4" ng-init="fromDt=false">
                    <input uib-datepicker-popup="yyyy-MM"
                           ng-click="fromDt=!fromDt" readonly="readonly"
						   datepicker-options="{minMode: 'month'}" datepicker-mode="'month'"
                           is-open="fromDt" show-button-bar="false" class="form-control"
                           placeholder="Select Month" ng-model="form.from" name="date"
                           required="required" type="text">
                </div>
				
                <div class="col-sm-4" ng-init="fromDt=false">
					<select class="form-control" ng-model="form.supplierList">
						<option value="" selected>-- <?php echo $this->translate('Supplier') ?> --</option>
						<option ng-repeat="option in supplierList"  value="{{option.id}}">{{option.name}}</option>
					</select>
				</div>
				
                <div class="col-sm-4">
                    <button class="btn btn-primary"
                            ng-class="{'btn-block loading-stripe': loading}" ng-disabled="loading" type="submit">
                        <span ng-hide="loading"><?php echo $this->translate('Generate') ?></span>
                        <span ng-show="loading"><?php echo $this->translate('Loading...') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="gap gap-small" ></div>
    <div id="collection-rpt-data" ng-hide="!collection.length">
        <div class="row list-view" align="center">
			<h1><span> 
				Selected Month : {{ form.from | date:'yyyy-MM '}} <br>
				Depot : {{selectedDepot}}
			</span></h1>
			
            <div class="col-lg-12">
                <table ng-init="invoice.total ={}" id="rpt-data-table" class="grid table table-condensed table-hover table-striped">
                    <thead>
                    <tr> 
                        <th> Departure Date</th>
                        <th> Arrival Date</th>
                        <th> BusNo.</th>
                        <th> Route</th>
                        <th> From City</th>
                        <th> To City</th>
                        <!-- <th> Depot</th> -->
                        <th align="right"> Number of Seats</th>
                        <th align="right"> Fare </th>
                        <th align="right"> Total Fare</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr ng-repeat="row in collection" ng-init="invoice=''">
                        <td>{{row.departureDateTime | date:'yyyy-MM-dd @ h:mma'}}</td>
                        <td>{{row.arrivalDatetime | date:'yyyy-MM-dd @ h:mma'}}</td>
						<td>{{row.busNo}}</td>
                        <td>{{row.route}}</td>
                        <td>{{row.fromCity}}</td>
                        <td>{{row.toCity}}</td>
                        <!-- <td>{{row.depot}}</td> -->
                        <td align="right">{{row.numberSeats}}</td>
                        <td align="right">{{row.fare  | number:2  }}</td>
                        <td align="right">{{row.totalFare  | number:2  }}</td>
                    </tr>
					
					<tr style="font-weight:bold">
						<td colspan="6" align="right">Total </td>
						<td align="right" >{{totalSeats }}</td>
						<td align="center" >-</td>
						<td align="right" >{{totalFare | currency : 'Rs. '}}</td>
					</tr>
					
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>