<?php
$public = getcwd() . '/public';
?>
<table>
    <tr>
        <td>
            Dear Valued Customer,<br/><br/>

            The online payment was successful!<br/>
            <b>Your seat is booked. eTicket No: ::bookingNo::</b><br/>
            Get ready to experience Sri Lanka, along the road!<br/><br/>

            Please check your mobile phone. You will receive the min-eTicket via SMS.<br/>
            Detailed eticket is attached to this email as a PDF, read the instructions carefully if you are using this service for the first time or not a frequent ::SITE_NAME:: traveller.
            <br/><br/>
            Take a moment to verify the reservation details related to eTicket ::bookingNo::.<br/><br/>
			Verification code: ::vCode:: <br/><br/>
            Service Route: ::departCity:: - ::arrivalCity::<br/>
            Journey Date: ::date::<br/>
            Journey Time: ::departureTime::<br/>
            Boarding Point: ::boardingLocation::<br/>
            Please reach your boarding place by: ::beThereAt::<br/>
            Service Provider: ::travels::<br/>
            Coach/ Bus Number: ::busNumber::<br/>
            Seat No: ::seatNumber::<br/>
            Total Fee: Rs. ::totalAmount::<br/><br/>

            Thank you for using ::SITE_NAME:: services!<br/>
            We are striving hard to serve you better.<br/><br/>

            Happy Travelling,<br/>
            ::SITE_NAME:: Team
        </td>
    </tr>
</table>
