<div>
    <div class="row">
        <div class="col-lg-12">
            <?php if (isset($error)): ?>
                <div class="alert alert-danger">
                      <strong>Error!</strong>
                      <?php echo $this->escapeHtml($error) ?>
                </div>
            <?php endif; ?>
            <div class="page-header">
                <span class="pull-right">
                    <span class="view_actions">
                        <a class="btn btn-default" href="<?php echo $this->url('legacy/default', array('controller'=> $controller)); ?>">
                            <span class="glyphicon glyphicon-list" aria-hidden="true">
                            </span>&nbsp;<span class="hidden-xs">List</span>
                        </a>
                    </span>
                    <span class="view_actions">
                        <a class="btn btn-default"
                            href="<?php echo $this->url('legacy/default', array('controller'=> $controller, 'action'=> 'view', 'id' => $model->id)); ?>">
                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true">
                            </span>&nbsp;<span class="hidden-xs">Show</span>
                        </a>
                    </span>
                </span>
                <h1><span>Edit booking "<?php echo $model->reference ?>"</span></h1>
            </div>
            <form action="<?php echo $this->url('legacy/default', array('controller'=> $controller, 'action'=> 'edit', 'id' => $model->id)); ?>" method="post">
                <div class="row form-horizontal" id="show-view">
                    <div class="col-lg-12 form-group">
                        <label class="col-sm-2 control-label">Remarks</label>
                        <div class="show-value col-sm-10 col-md-8 col-lg-7">
                            <textarea id="remarks" name="remarks" class="form-control" autocomplete="off"
                                style="z-index: auto; position: relative; line-height: 20px; font-size: 14px;
                                transition: none; background: transparent !important;"><?php echo $this->escapeHtml($model->remarks); ?></textarea>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button name="update" value="1" type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-ok"></span> Save Changes
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>