
<h5 class="header-text bold-text">Users</h5>

<form ng-submit="search()">
    <fieldset>
        <table width="100%">
            <tr>
                <td><label>Name: </label></td>
                <td style="padding-right:10px;"><input ng-model="form.name" type="text"/></td>
                <td><label>Email : </label></td>
                <td><input type="text" ng-model="form.email"/></td>
            </tr>
            <tr>
                <td align="right" colspan="3"></td>
                <td><button class="btn btn-primary-custom">Search</button></td>
            </tr>
        </table>
    </fieldset>
</form>

<div loading-container="tableParams.settings().$loading">
    <table ng-table="tableParams" class="table resulttable" template-pagination="searchTablePager">
        <tbody>
        <tr ng-repeat="bus in $data" show-seats>
            <!-- main row -->
            <td data-title="'Name'">
                <b>{{bus.first_name}} {{bus.last_name}}</b>
            </td>
            <td data-title="'Email'">
                {{bus.email}}
            </td>
            <td data-title="'Mobile Number'">
                {{bus.mobile_number}}
            </td>
            <td data-title="'Gender'">
                {{bus.gender}}
            </td>
            <td data-title="'Role'">
                {{bus.role}}
            </td>

        </tr>
        <tr ng-show="!$data.length">
            <td colspan="10"><b class="">No Results!</b> <span class="text-muted"> - Can't find a record. Try again.</span></td>
        </tr>
        </tbody>
    </table>
</div>

<script type="text/ng-template" id="searchTablePager">
    <ul class="pagination ng-table-pagination">
        <li ng-class="{'disabled': !page.active}" ng-repeat="page in pages" ng-switch="page.type">
            <a ng-switch-when="prev" ng-click="params.page(page.number)" href="">&laquo;</a>
            <a ng-switch-when="first" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a>
            <a ng-switch-when="page" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a>
            <a ng-switch-when="more" ng-click="params.page(page.number)" href="">&#8230;</a>
            <a ng-switch-when="last" ng-click="params.page(page.number)" href=""><span ng-bind="page.number"></span></a>
            <a ng-switch-when="next" ng-click="params.page(page.number)" href="">&raquo;</a>
        </li>
    </ul>
</script>