<div class="srx-home-content hidden-xs">
    <div class="container">
        <div class="srx-home-box">
            <h2>Surrexi Travels</h2>
            <h4>Travel in passion.</h4>
            <p>We provide super comfort tour and public transport services via both scheduled and on-demand modes across Sri Lanka. Surrexi Travels is one of the leading players in travel and hospitality industry providing services with a well-disciplined set of staff who value passenger happiness, throughout the journey.</p>
        </div>
    </div>
    <div class="gap"></div>
</div>

