<div>
    <div class="row list-header">
        <div class="col-lg-12">
            <div class="page-header">
            	<span class="pull-right">
                    <span class="view_actions">
                        <a class="btn btn-default" href="<?php echo $this->url('legacy/default', array('controller'=> $controller, 'action'=> 'create')); ?>">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true">
                            </span>&nbsp;<span class="hidden-xs">Create</span>
                        </a>
                    </span>
                </span>
                <h1><span>Users</span></h1>
            </div>
        </div>
    </div>
    <div class="row">
        <form action="<?php echo $this->url('legacy/default', array('controller'=> $controller)) ?>"
            method="get" class="filters col-md-offset-6 col-md-6 form-horizontal">
            <?php foreach ($this->filters as $filter): ?>
                <div class="filter form-group input-string">
                <label for="<?php echo $filter['name'] ?>" class="col-sm-4 col-xs-11 control-label"><?php echo $filter['label'] ?>&nbsp;</label>
                <div class="col-sm-7">
                    <input type="text" id="<?php echo $filter['name'] ?>" name="<?php echo $filter['name'] ?>" class="form-control"
                        placeholder="<?php echo $filter['placeholder'] ?>" autocomplete="off" onchange="this.form.submit()"
                        value="<?php echo $this->escapeHtml(!empty($this->params[$filter['name']])
                                ? $this->params[$filter['name']] : ''); ?>">
                </div>
            </div>
            <?php endforeach; ?>
        </form>
    </div>
    <div>
        <div class="row list-view">
            <div class="col-lg-12">
                <table class="grid table table-condensed table-hover table-striped">
                    <thead>
                        <tr>
                        <?php foreach ($this->headers as $field => $label): ?>
                            <th>
                                <?php
                                    $params = $this->params;
                                    if (isset($params['sortField']) && $params['sortField'] == $field
                                            && isset($params['sortDir']) && $params['sortDir'] == 'ASC') {
                                        $params['sortDir'] = 'DESC';
                                    } else {
                                        $params['sortDir'] = 'ASC';
                                    }
                                    $params['sortField'] = $field;
                                ?>
                                <a href="<?php echo $this->url('legacy/default', array('controller' => $controller)) . '?' . http_build_query($params); ?>">
                                    <?php if (isset($this->params['sortField']) && $this->params['sortField'] == $field): ?>
                                        <?php if (isset($this->params['sortDir']) && $this->params['sortDir'] == 'DESC'): ?>
                                            <span class="glyphicon glyphicon-chevron-down"></span>
                                        <?php else: ?>
                                            <span class="glyphicon glyphicon-chevron-up"></span>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                    <?php echo $label; ?>
                                </a>
                            </th>
                        <?php endforeach; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php /* @var $entity \Api\Client\Soap\Core\UserLight */ foreach ($this->paginator as $entity) : ?>
                            <tr>
                                <td><?php echo $this->escapeHtml($entity->username) ?></td>
                                <td><?php echo $this->escapeHtml($entity->firstName) ?></td>
                                <td><?php echo $this->escapeHtml($entity->lastName) ?></td>
                                <td>
                                    <span>
                                        <a class="btn btn-default btn-xs" href="<?php echo $this->url('legacy/default', array('controller'=> $controller, 'action'=> 'view', 'id' => $entity->id)); ?>">
                                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&nbsp;<span class="hidden-xs ng-binding">Show</span>
                                        </a>
                                    </span>
                                    <span>
                                        <a class="btn btn-default btn-xs" href="<?php echo $this->url('legacy/default', array('controller'=> $controller, 'action'=> 'edit', 'id' => $entity->id)); ?>">
                                            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;<span class="hidden-xs ng-binding">Edit</span>
                                        </a>
                                    </span>
                                    <span>
                                        <a class="btn btn-default btn-xs" href="<?php echo $this->url('legacy/default', array('controller'=> $controller, 'action'=> 'resetpassword', 'id' => $entity->id)); ?>">
                                            <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>&nbsp;<span class="hidden-xs ng-binding">Change PW</span>
                                        </a>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div>
        <div class="col-lg-12">
            <nav class="pagination-bar">
                <?php echo $this->paginationControl(
                     $this->paginator,
                    'sliding',
                    'partial/paginator.phtml',
                    array(
                        'route' => 'legacy/default',
                        'controller' => $controller,
                        'params' => $this->params,
                    )
                ); ?>
            </nav>
        </div>
    </div>
</div>