<div>
    <div class="row">
        <div class="col-lg-12">
            <?php if (isset($error)): ?>
                <div class="alert alert-danger">
                      <strong>Error!</strong>
                      <?php echo $this->escapeHtml($error) ?>
                </div>
            <?php endif; ?>
            <div class="page-header">
                <span class="pull-right">
                    <span class="view_actions">
                        <a class="btn btn-default" href="<?php echo $this->url('legacy/default', array('controller'=> $controller)); ?>">
                            <span class="glyphicon glyphicon-list" aria-hidden="true">
                            </span>&nbsp;<span class="hidden-xs">List</span>
                        </a>
                    </span>
                </span>
                <h1><span>Change user password</span></h1>
            </div>
            <form action="" method="post">
                <div class="row form-horizontal" id="show-view">
                    <div class="col-lg-12 form-group">
                        <label class="col-sm-2 control-label">User</label>
                        <div class="show-value col-sm-10 col-md-8 col-lg-7">
                            <div class="form-control-static"><?php echo $this->escapeHtml($model->firstName .' '. $model->lastName); ?> - <?php echo $this->escapeHtml($model->username); ?></div>

                        </div>
                    </div>
                    <div class="col-lg-12 form-group">
                        <label class="col-sm-2 control-label">New Password&nbsp;*</label>
                        <div class="show-value col-sm-10 col-md-8 col-lg-7">
                            <input type="password" id="password1" name="password1" class="form-control" required="required" autocomplete="off" />
                        </div>
                    </div>
                    <div class="col-lg-12 form-group">
                        <label class="col-sm-2 control-label">Repeat password&nbsp;*</label>
                        <div class="show-value col-sm-10 col-md-8 col-lg-7">
                            <input type="password" id="password2" name="password2" class="form-control" required="required" autocomplete="off" />
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button name="update" value="1" type="submit" class="btn btn-primary">
                            <span class="glyphicon glyphicon-ok"></span> Change Password
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>