<div>
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <span class="pull-right">
                    <span class="view_actions">
                        <a class="btn btn-default" href="<?php echo $this->url('legacy/default', array('controller'=> $controller)); ?>">
                            <span class="glyphicon glyphicon-list" aria-hidden="true">
                            </span>&nbsp;<span class="hidden-xs">List</span>
                        </a>
                    </span>
                    <span class="view_actions">
                        <a class="btn btn-default"
                            href="<?php echo $this->url('legacy/default', array('controller'=> $controller, 'action'=> 'edit', 'id' => $model->id)); ?>">
                            <span class="glyphicon glyphicon-pencil" aria-hidden="true">
                            </span>&nbsp;<span class="hidden-xs">Edit</span>
                        </a>
                    </span>
                </span>
                <h1><span>User "<?php echo $model->username ?>"</span></h1>
            </div>
            <div class="row form-horizontal" id="show-view">
                <div class="col-lg-12 form-group">
                    <label class="col-sm-2 control-label">ID</label>
                    <div class="show-value col-sm-10 col-md-8 col-lg-7"><span><?php echo $this->escapeHtml($model->id) ?></span></div>
                </div>
                <div class="col-lg-12 form-group">
                    <label class="col-sm-2 control-label">First name</label>
                    <div class="show-value col-sm-10 col-md-8 col-lg-7"><span><?php echo $this->escapeHtml($model->firstName) ?></span></div>
                </div>
                <div class="col-lg-12 form-group">
                    <label class="col-sm-2 control-label">Last name</label>
                    <div class="show-value col-sm-10 col-md-8 col-lg-7"><span><?php echo $this->escapeHtml($model->lastName) ?></span></div>
                </div>
                <div class="col-lg-12 form-group">
                    <label class="col-sm-2 control-label">Email</label>
                    <div class="show-value col-sm-10 col-md-8 col-lg-7"><span><?php echo $this->escapeHtml($model->email) ?></span></div>
                </div>
                <div class="col-lg-12 form-group">
                    <label class="col-sm-2 control-label">Mobile</label>
                    <div class="show-value col-sm-10 col-md-8 col-lg-7"><span><?php echo $this->escapeHtml($model->mobileTelephone) ?></span></div>
                </div>
                <div class="col-lg-12 form-group">
                    <label class="col-sm-2 control-label">Status</label>
                    <div class="show-value col-sm-10 col-md-8 col-lg-7"><span><?php echo $this->escapeHtml($model->status->name) ?></span></div>
                </div>
                <div class="col-lg-12 form-group">
                    <label class="col-sm-2 control-label">Roles</label>
                    <div class="show-value col-sm-10 col-md-8 col-lg-7"><span><?php echo $this->escapeHtml(implode(', ', array_map(function($ug) { return $ug->name; }, $model->userGroups))) ?></span></div>
                </div>
            </div>
        </div>
    </div>
</div>