<script>
    jQuery(function($) {
        if ($('#map-canvas').length) {
            var map,
                service;

            var latlng = new google.maps.LatLng(6.886414, 79.886865);
            var myOptions = {
                zoom: 16,
                center: latlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                scrollwheel: false
            };

            map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);


            var marker = new google.maps.Marker({
                position: latlng,
                map: map
            });
            marker.setMap(map);


            $('a[href="#google-map-tab"]').on('shown.bs.tab', function (e) {
                google.maps.event.trigger(map, 'resize');
                map.setCenter(latlng);
            });
        }
    });
</script>

<div class="container">
    <h1 class="page-title"><?php echo $this->translate('Contact Us') ?></h1>
</div>

<div class="container">
</div>
<div id="map-canvas" style="height:400px;"></div>
<div class="container">
    <div class="gap"></div>
    <div class="row">
        <div class="col-md-7">
            <p><?php echo $this->translate('Contact Us body text') ?></p>
<!--            <form class="mt30">-->
<!--                <div class="row">-->
<!--                    <div class="col-md-6">-->
<!--                        <div class="form-group">-->
<!--                            <label>Name</label>-->
<!--                            <input class="form-control" type="text" />-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="col-md-6">-->
<!--                        <div class="form-group">-->
<!--                            <label>E-mail</label>-->
<!--                            <input class="form-control" type="text" />-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="form-group">-->
<!--                    <label>Message</label>-->
<!--                    <textarea class="form-control"></textarea>-->
<!--                </div>-->
<!--                <input class="btn btn-primary" type="submit" value="Send Message" />-->
<!--            </form>-->
        </div>
        <div class="col-md-4">
            <aside class="sidebar-right">
                <ul class="address-list list">
                    <li>
                        <h5><?php echo $this->translate('Email') ?></h5><a href="mailto:info@busbooking.lk">info@busbooking.lk</a>
                    </li>
                    <li>
                        <h5><?php echo $this->translate('Phone Number') ?></h5><a href="#">0115-116-117</a>
                    </li>
                    <!--<li>
                        <h5><?php echo $this->translate('Address') ?></h5>
                        <address>
                            <?php echo $this->translate('Level 34, East Tower,<br />
                            World Trade Centre,<br />
                            Echelon Square, Colombo 01,<br />
                            Sri Lanka') ?>
                        </address>
                    </li>-->
                </ul>
            </aside>
        </div>
    </div>
    <div class="gap"></div>
</div>